<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VisionFlow.Base\VisionFlow.Base.csproj" />
    <ProjectReference Include="..\VisionFlow.Tools\VisionFlow.Tools.csproj" />
    <ProjectReference Include="..\VisionFlow.ToolEditors\VisionFlow.ToolEditors.csproj" />
    <ProjectReference Include="..\VisionFlow.Controls\VisionFlow.Controls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\lib\halcon\halcondotnet.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>