<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\lib\halcon\halcondotnet.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
